name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up environment variables
      env:
        DB_URL: ${{ secrets.DB_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: echo "Environment variables set."

    - name: Build with Gradle
      run: ./gradlew build -x test


    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/wsb
          git pull origin main
          chmod +x ./gradlew
          ./gradlew build
          pkill -f bcube-0.0.1-SNAPSHOT.jar || true
          nohup java -jar bcube-0.0.1-SNAPSHOT.jar --spring.profiles.active=server > app.log 2>&1 &
