name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle

    - name: Build with Gradle (skip tests)
      run: ./gradlew build -x test

    - name: Test SSH Connection
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          echo "SSH connection successful."


    - name: Deploy to Server via SCP
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "build/libs/wsb-0.0.1-SNAPSHOT.jar"
        target: "/home/ubuntu/wsb/wsb-0.0.1-SNAPSHOT.jar"
        debug: true

    - name: Restart Application via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          # 기존 애플리케이션 종료
          pkill -f wsb-0.0.1-SNAPSHOT.jar || true
          
          # 새 애플리케이션 실행
          nohup java -jar /home/ubuntu/wsb/wsb-0.0.1-SNAPSHOT.jar --spring.profiles.active=server > /home/ubuntu/wsb/app.log 2>&1 &
          
          # 실행 확인 (옵션)
          sleep 5
          if pgrep -f wsb-0.0.1-SNAPSHOT.jar; then
            echo "Application started successfully."
          else
            echo "Application failed to start. Check app.log for details."
            cat /home/ubuntu/wsb/app.log
            exit 1
          fi
